schema_version: '1.0'
project_id: yt-YP0FDR7Wc-8
source:
  url: https://www.youtube.com/watch?v=YP0FDR7Wc-8
  channel: null
  title: null
target_languages:
- en
- ar
- fa
- ur
- zh
- fr
- es
- pt
- ru
audio_languages:
- en
- zh
- fr
- es
- pt
- ru
dubbing:
  voice_clone: false
glossary_id: null
join_clips: true
selection: null
created_at: '2026-08-04T11:37:35Z'
